it:
  it-it
uk:
  en-gb
fr:
  fr-fr
de:
  de-de
es:
  es-es
at:
  de-at
be:
  en-be
ch:
  en-ch
ie:
  en-ie
int:
  en
nl:
  en-nl
"no":
  en-no
se:
  en-se
fi:
  en-fi
dk:
  en-dk
pt:
  en-pt
cz:
  en-cz
hu:
  en-hu
pl:
  en-pl
bg:
  en-bg
ro:
  en-ro
tr:
  en-tr
ae:
  en-ae
kr:
  kr-kr
jp:
  ja-jp
cn:
  zh-cn
cn-en:
  en-cn
